### PR TITLE
update to v0.152.3 + fix x-checker-data

### PR DESCRIPTION
**Pull request by tomaswarynyca**
Now you can use this command to update
`flatpak run org.flathub.flatpak-external-data-checker --edit-only ./dev.zed.Zed.yaml`

### CODE REVIEW

**Comment by tomaswarynyca** [comment]
@ShobuPrime can you check this please?

**Comment by rashadgasimli** [comment]
> Build [145557 successful](https://buildbot.flathub.org/#/builders/6/builds/145557) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/128643/dev.zed.Zed.flatpakref
> ```

the link not working anymore

**Comment by tomaswarynyca** [comment]
@bbhtt can you check this please?
Also, once you merge this, can you configure flathubbot to generate the PRs automatically?

**Comment by bbhtt** [comment]
X-checker runs for all repos hourly it will generate PRs automatically. You only need the relevant x-checker stanza in the manifest to make it work

**Comment by ShobuPrime** [comment]
> @ShobuPrime can you check this please? I would also appreciate if you consider that I can have access to be maintainer of the project so I don't have to be bothering you to update it - you would have to create an issue requesting to add me to the repo in [flathub/flathub](https://github.com/flathub/flathub/issues)

Based on [this comment](https://github.com/flathub/flathub/pull/5253/files/39ce906b9f04d100f54e1e3287bae1fc0a77ccd8#r1689052143), @bbhtt mentioned automatic PR merges weren't allowed anymore (at least from the perspective of `flathub.json`.

@bbhtt -- If we were to build a Github action to check if a PR is simply updating the hash and version numbers correctly and automatically merge that way, is that allowed?

As for being an additional maintainer, based on [this comment](https://github.com/flathub/flathub/pull/5253#issuecomment-2254605263) we will need to:

> Create an issue at https://github.com/flathub/flathub/ detailing who needs inviting (or removing) and someone will handle it.

**Comment by tomaswarynyca** [comment]
Now that this PR modifies “x-checker-data” with a working config, flathubbot will check every 1hs if a new version exists and will generate a PR if necessary. That modifies the version and sha256 - causing the bot to generate a new build to verify that it works properly and have a PR ready to be merged.

**Comment by bbhtt** [comment]
Yes whenever a new version is released upstream the bot will submit a PR with an update. You just need to merge it. There is no need for any GitHub action.

**Review by ShobuPrime — APPROVED** [review]

**Pull request merged**
